#!/bin/sh

# optionally take a kernel bzImage as a parameter
if [ -n "$1" ]; then
  KERNEL_PART="-kernel $1 -append root=/dev/sda3"
fi

QEMU=$(which qemu 2>/dev/null || which qemu-system-x86_64 2>/dev/null)

$QEMU -hda alpine-kernel-dev/alpine-kernel-dev \
  -net nic -net bridge,br=br0 \
  -m 2GB -s $KERNEL_PART
