#!/bin/sh

# optionally take a kernel bzImage as a parameter
if [ -n "$1" ]; then
  KERNEL_PART="-kernel $1 -append root=/dev/sda3"
fi

QEMU=$(command -v qemu 2>/dev/null || command -v qemu-system-x86_64 2>/dev/null)
IMG=$(find images/ -name '*.qcow2' |tail -1)

$QEMU -accel kvm -hda "$IMG" -nographic
